name: ci

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

  eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        # Enable linters
        eslint: true
        eslint_extensions: ts
        # prettier: true

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run unit tests
      uses: actions/checkout@v2
      run: npm run unit-tests
      with:
        github_token: ${{ secrets.github_token }}